### ISSUE TITLE
save grammarly login for future sessions

### ISSUE THREAD

**Issue by HumHongeKamyaab** [emacs-grammarly/lsp-grammarly#18]
I observed that the user need to login to the grammarly everytime new lsp session is started using lsp-grammarly. 
Is it possible to save the login information for all the future sessions.

**Comment by jcs090218** [comment]
Ah, no. [Grammarly.com]() gave us the cookie with the expires date. You would not need to re-login until your cookie is expired!

I am going to close this issue since this isn't true. Feel free to open other issue if you have other questions! 👍

**Comment by HumHongeKamyaab** [comment]
May be I didnt setup the login correctly and it is also the reason for issue #19 

I always get `[INFO] Visited as, anonymous` in message buffer whenever new Grammarly lsp session is started.

**Comment by HumHongeKamyaab** [comment]
I have found another instance of `emacs-grammarly` installed on my system path other than  installed by `straight.el`. Maybe it is the source of all errors.

**Comment by jcs090218** [comment]
> I always get [INFO] Visited as, anonymous in message buffer whenever new Grammarly lsp session is started.

Yeah, this doesn't seem right. Make sure you are login correctly. Maybe you miss some steps [here](https://github.com/emacs-grammarly/lsp-grammarly#money_with_wings-using-a-paid-grammarly-account)?

Alternatively, you can try login with VSCode since the both plugins uses the same seesion.

**Comment by HumHongeKamyaab** [comment]
@jcs090218  I am following all the steps correctly and made it work properly with login and verify the login also using #19 . But somehow in future Emacs session, I need to log in again and verification fails. This happens after system restart.

Can you steps to debug the issue live in emacs. I want to see which commands lsp-grammrly is exactly running to call grammarly. May be it is running another instance of server which I am unable to find. Also can you tell me where the cookie is saved in the emacs directory. I could not find location of it.

**Comment by jcs090218** [comment]
> Can you tell me steps to debug the issue live in emacs.

This comment should answer your question, see https://github.com/emacs-grammarly/lsp-grammarly/issues/19#issuecomment-905441334.

> Also, can you tell me where the cookie is saved in the Emacs directory. I could not find the location of it.

The cookie is saved with [keytar](https://github.com/emacs-grammarly/keytar), so it is due to different platforms. I am using windows hence it stores using [credential manager](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0). Check out the upstream [atom/keytar](https://www.npmjs.com/package/keytar) should help! 👍 

---

If you still having troubles, see vscode client and language server implementation [here](https://github.com/emacs-grammarly/unofficial-grammarly-language-server/blob/main/extension/src/services/AuthenticationService.ts). Hope these information would help!
