### ISSUE TITLE
Grammarly login

### ISSUE THREAD

**Issue by MathieuDutSik** [emacs-grammarly/lsp-grammarly#53]
I am trying to install the `lsp-grammarly` for emacs and I face a number of issues:
* First the `README.md` gives some information about the paid login but it says nothing about the free account login. Maybe this follow the same process but this ought to be said.
* The `use-package` is actually an external package that should be installed separately (for example with MELPA) and that ought to be said I think.
* When calling the `M-x lsp-grammarly-login` it is said that _you should see the Grammarly's website pop out from your favorite browser_ and instead I get the far less pretty _The connected server(s) does not support method $/isUserAccountConnected.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section_.
* About the **Grammarly Extension Settings** I find the documentation pretty underwhelming. Listing all the options is not enlightening. A simple question, should I create the `package.json` and put it in the `.emacs.d` directory?
* Could we get screenshot showing when `lsp-grammarly` works correctly? That could help the user know what he can get.

In general anything that could help the installation would be very much welcomed.

**Comment by jcs090218** [comment]
> * First the README.md gives some information about the paid login but it says nothing about the free account login. Maybe this follow the same process but this ought to be said.

There is no reason for you to login for free account since the default is free version (weather you logged in or not).

> * The use-package is actually an external package that should be installed separately (for example with MELPA) and that ought to be said I think.

It's built-in after 29.1. Many people recommend to see `use-package` for installation and usage, so I have it by default. Here is the built-in way before 29.1.

```elisp
(add-hook 'text-mode-hook 
          (lambda ()
            (require 'lsp-grammarly)
            (lsp)))
```

Feel free to open up a PR for this. ;)

> * When calling the M-x lsp-grammarly-login it is said that you should see the Grammarly's website pop out from your favorite browser and instead I get the far less pretty The connected server(s) does not support method $/isUserAccountConnected.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section.

We are migrating from the old language server (see [unofficial-grammarly-language-server](https://github.com/emacs-grammarly/unofficial-grammarly-language-server) to the newer and the official [grammarly-language-server](https://github.com/emacs-grammarly/grammarly-language-server)). Short answer is, we don't have way to login anymore since the login is only available in VSCode. :(

But I'm trying to add those features back, see #53.

> * About the Grammarly Extension Settings I find the documentation pretty underwhelming. Listing all the options is not enlightening. A simple question, should I create the package.json and put it in the .emacs.d directory?

No, all settings should be in elisp. This is the default way to configure language servers from client with `lsp-mode`. You can see their [manual page](https://emacs-lsp.github.io/lsp-mode/) for more information.

> * Could we get screenshot showing when lsp-grammarly works correctly? That could help the user know what he can get.

There is a screenshot in the README page, isn't that enough? 🤔

**Comment by MathieuDutSik** [comment]
Thank you for your precisions. I will indeed provide a PR with some proposed corrections. For the emacs version, the latest one is 28.2 as of June 2023. So, I am not sure what you mean with "built-in after 29.1".

So, `lsp-grammarly` for the free account should work right out of the box after installation?

**Comment by jcs090218** [comment]
> So, I am not sure what you mean with "built-in after 29.1".

Oh, I am using the snapshot version 29.0.92, and it has `use-package` built-in. I said 29.1 since that is the official release version number.

> So, lsp-grammarly for the free account should work right out of the box after installation?

Yes. 👍

**Comment by MathieuDutSik** [comment]
Thank you, I created a corresponding PR on README.md based on the discussion.
