### ISSUE TITLE
a question/feature request: ignore text within latex commands such as \label{text here}

### ISSUE THREAD

**Issue by eli-tziperman** [emacs-grammarly/lsp-grammarly#60]
This package is a life server. Thank you! I use it in LaTeX (AUCTeX), and I was wondering if it is possible to make it recognize some latex commands where grammar checking is not needed. Specifically, for example, if I have a \label{some text here} or \ref{some text here}, it would be best if Grammarly just ignored these. Is there a way to do so?

**Comment by jcs090218** [comment]
No, unfortunately. The upstream language server doesn't officially support LaTeX. You can try opening up a feature request over there ––– [grammarly](https://github.com/znck/grammarly) language server, but AFAIK, the author is very busy with something else. 🤔 

I'm closing this issue since there is nothing to do with the language client!

**Comment by jcs090218** [comment]
FYI, the ideal solution is to use the tree-sitter to extract the content from the code. That's how the language server is working right now; see https://github.com/znck/grammarly?tab=readme-ov-file#adding-support-for-new-language.
