### ISSUE TITLE
Doesn't work with no file buffers

### ISSUE THREAD

**Issue by agzam** [emacs-grammarly/lsp-grammarly#8]
It looks like it doesn't work with buffers that have no associated file. In order for the package to work a buffer, it **must** have a file. How difficult would it be to make it work in "ephemeral" buffers, e.g.: `*scratch*`?

**Comment by jcs090218** [comment]
Ah, yes. That's how language server work. I think you would also need to be inside a project in order to start the language server? I don't know if it is possible to have it enable in buffer like `*scratch*`.

If VSCode grammarly works in any file (even outside of project) then this might be an feature to `lap-mode`.

**Comment by agzam** [comment]
Alright, that makes sense. I'm going to close this for now, since this is an upstream issue. I'll try to figure out a workaround, and update it once (if) I find one.

**Comment by jcs090218** [comment]
You can leave this issue open if you want. I would also like this to work! :D

**Comment by agzam** [comment]
@yoncho says: "the buffer has to have a buffer-name". So I ended up doing something like: `(set-visited-file-name (format "/tmp/%s" random-name))`
